[package]
name = "swaps-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib_deploy.rs"

[features]
no-entrypoint = []
default = []

[dependencies]
solana-program = "1.14"
