[features]
seeds = false
skip-lint = false
[programs.localnet]
swaps_deploy = "Eqr7xLt9rbGauuBi3xKKA6drYx1MuKGYhwko9eAWjUPw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/pat.dentico/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
